### ISSUE TITLE
kr server not working

### ISSUE THREAD

**Issue by domesticatedTREE** [austinyen56/League-of-Legends-Language-Changer#2]
" set /p comm=Enter server name(na/lan/brazil/eune/euw/las/oce/russia/turkey/japan): "
the option for kr server is not present.

**Comment by austinyen56** [comment]
The KR server isn't included in the riot client (they have their own separate client I think) and I currently do not have a KR account. So I am unable to test it out. However, if you want to try it yourself, you can just edit out of of the entries (such as oce) and replace them all with kr. If it worked, let me know so I can add it in officially :))
