### ISSUE TITLE
RE: is the upcoming Southeast Asia server supported?

### ISSUE THREAD

**Issue by lucentshade** [austinyen56/League-of-Legends-Language-Changer#3]
Hi, would like to know if you can kindly update for supporting SEA regions?

Much appreciated <3

**Comment by austinyen56** [comment]
Yea I will definitely update it once the Garena to Riot switch is in place (Earliest 11/18)!

**Comment by lucentshade** [comment]
Thanks and have a nice day!

Austin Yen ***@***.***> 于 2022年11月14日周一 04:01写道：

**Comment by lucentshade** [comment]
Hi, the servers officially launched on 6/1, kindly add the support for SG servers ^_^

Thank you very much

**Comment by austinyen56** [comment]
Updated just now for SEA servers! Server selection is no longer required since everything is run through Riot Client.

**Comment by lucentshade** [comment]
Hi Austin, is it possible to have the client in Chinese(China) but landing page and all shops still connected to local region?
Because now it's unable to show anything at landing page..
![2023-01-13 17_23_11-Window](https://user-images.githubusercontent.com/118102849/212284639-8da79466-881f-4662-96d0-4c414f21d0f4.png)

**Comment by austinyen56** [comment]
Unfortunately, as of now, I don't think it is possible because China has its own servers (I think) and the main page is different from the Riot ones. However, the shop functions should still work as usual

**Comment by lucentshade** [comment]
yes from what I observed, if I set the language to Chinese_Malaysia, the
landing page works normally, is it possible to use Chinese_China while
connected to local server (SG) landing page?

Just asking if it's technically possible or not, thanks for your
prompt reply!
