### ISSUE TITLE
--locale not working anymore?

### ISSUE THREAD

**Issue by f0rmat1k** [austinyen56/League-of-Legends-Language-Changer#5]
tow problem:
1. Script doesnt generate shortcut on desktop. I dont know why (win11, also tried admin mode)
2. looks like --locale doesnt work anymore

**Comment by austinyen56** [comment]
Did it work before? I just tried it on my win 11 virtual machine (I use win10 as my main PC) and I can confirm it still works. Did you try changing the default directory?
Default path should be ```C:\Riot Games\LeagueClient.exe```
To edit, just right click on the bat script, "edit", and then under ```set dir="..."```, just the path above

Hope that helps!
